# Generated by Django 4.2.27 on 2026-01-25 07:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tenders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_number', models.CharField(editable=False, help_text='Auto-generated tender number', max_length=20, unique=True)),
                ('tender_title', models.CharField(help_text='Title/name of the tender', max_length=255)),
                ('oil_type', models.CharField(choices=[('crude', 'Crude Cinnamon Oil'), ('refined', 'Refined Cinnamon Oil'), ('organic', 'Organic Cinnamon Oil'), ('conventional', 'Conventional Cinnamon Oil')], help_text='Type of cinnamon oil', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in liters or kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quality_grade', models.CharField(blank=True, help_text='Quality grade (A+, A, B, C, etc.) - Auto-generated from ML model', max_length=10, null=True)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, help_text='Quality score from ML model (0-100)', max_digits=5, null=True)),
                ('tender_description', models.TextField(help_text='Detailed description of the tender')),
                ('report_file', models.FileField(help_text='Upload oil quality report (PDF, DOC, XLS, or Image)', upload_to=tenders.models.tender_report_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg'])])),
                ('start_date', models.DateField(help_text='Tender start date')),
                ('end_date', models.DateField(help_text='Tender end date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('awarded', 'Awarded')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(limit_choices_to={'role': 'manufacturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tender',
                'verbose_name_plural': 'Tenders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, help_text='Bid amount per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('message', models.TextField(blank=True, help_text='Optional message to manufacturer')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tenders.tender')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tender', 'buyer')},
            },
        ),
    ]
