# Generated by Django 4.2.27 on 2026-04-27 05:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity in liters or kg', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='tenderbid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, help_text='Bid amount per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
