# Generated by Django 4.2.27 on 2026-03-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer'), ('buyer', 'Buyer'), ('admin', 'Admin')], default='', help_text='User role: manufacturer, buyer, or admin', max_length=20),
        ),
    ]
